version: '3.8'

services:
  video-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-generation-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data/outputs:/mnt/tank/scratch/edubskiy/outputs
      - ./data/huggingface_cache:/mnt/tank/scratch/edubskiy/huggingface_cache
      - ./data/models:/app/models
    environment:
      - SCRIPT_PATH=/app/task.sh
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-storage.modera.fashion}
      - S3_REGION=${S3_REGION:-eu-central-2}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - OUTPUT_BASE_DIR=/mnt/tank/scratch/edubskiy/outputs
      - HF_HOME=/mnt/tank/scratch/edubskiy/huggingface_cache
      - TRANSFORMERS_CACHE=/mnt/tank/scratch/edubskiy/huggingface_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  default:
    driver: bridge 